### ISSUE TITLE
Can you implement discovery function?

### ISSUE THREAD

**Issue by GermanBluefox** [unltdnetworx/ioBroker.energymanager#1]
Device is reachable via IP, so it can be detected by discovery adapter.
Examples are here: https://github.com/ioBroker/ioBroker.discovery/tree/master/lib/adapters

**Comment by unltdnetworx** [comment]
I'm on it.

**Comment by unltdnetworx** [comment]
Created a pull request for discovery adapter with pattern for the energymanager hardware.
