### ISSUE TITLE
error property 'deviceClass' of undefined

### ISSUE THREAD

**Issue by arteck** [unltdnetworx/ioBroker.energymanager#13]
check this plz

![grafik](https://user-images.githubusercontent.com/6681528/66806779-ae173e80-ef28-11e9-9345-d586a8900145.png)

**Comment by unltdnetworx** [comment]
The IP-adress is correct defined? Other datapoints are working?

**Comment by arteck** [comment]
yes.. look forum

**Comment by unltdnetworx** [comment]
Should be fixed. Please close this issue, if so.

**Comment by unltdnetworx** [comment]
New attempt. Please try again.

**Comment by unltdnetworx** [comment]
Fixed
