### ISSUE TITLE
Kein Fehler nur eine Frage

### ISSUE THREAD

**Issue by flinke-flasche** [unltdnetworx/ioBroker.energymanager#15]
Hallo,
dein Adapter läuft prima. Danke.Vielleicht kannst du mir helfen?

Ich hatte dieses Jahr schon 2x das Problem, dass mein Speicher ein Problem hatte und mehrere Tage nicht funktionierte. Leider bekommt man das erst nach ein paar Tagen oder sogar Wochen mit, da ich nicht jeden Tag zum Speicher schaue, was sehr schade ist.

Gibt es einen Wert bei dem man sieht ob der Speicher funktioniert oder einen Error hat?
Dann könnte ich mir mit einem Script eine Nachricht schicken lassen falls er wieder ausgefallen ist.

Grüße
Tobias

**Comment by unltdnetworx** [comment]
Hallo,
ja einen solchen Wert gibt es tatsächlich. Sogar für jede Komponente des Systems. Der Datenounkt nennt sich "StateDevice" und kann entweder "OK" oder "ERROR" sein.

In meinem Fall für den Speicher: "energymanager.0.Batteriekonverter_(EON_Aura).StateDevice"
