### ISSUE TITLE
Adapter lässt Anlage Abstürzen

### ISSUE THREAD

**Issue by flinke-flasche** [unltdnetworx/ioBroker.energymanager#20]
Ich habe seit kurzem das Problem, dass wenn ich den Adapter laufen lasse, meine Geräte der Photovoltaikanlage Verbindungsprobleme mit dem Aura Manager haben und somit meine Anlage nicht richtig arbeiten kann.

Dieser Fehler kam plötzlich.
Kann das ein einem Firmware Update am Aura Manager liegen?

**Comment by unltdnetworx** [comment]
Welche Version hat die Firmware im Energymanager? Meine E.on Anlage hat 7.32.1.0 und läuft seit aktuell 27 Tagen durch ohne Probleme.

Wenn keine Änderungen an ioBroker oder den Adapter Einstellungen gemacht wurden (Update, kürzere Abholintervalle, etc.) muss es ja fast am System liegen.

Evtl. mal im ioBroker Forum eine Anfrage starten, ob noch jemand ein Problem hat. Falls es neue Erkenntnisse gibt, bitte diesen Issue wieder öffnen. Momentan kann ich aber leider keinen Fehler erkennen.
