### ISSUE TITLE
enviaM Energiemanager liefert keine Daten

### ISSUE THREAD

**Issue by Smarty0815** [unltdnetworx/ioBroker.energymanager#38]
Ich habe bei mir den Energymanager von enviaM im Einsatz. Leider werden hier keine Daten geliefert.

Im Log steht immer nur "null".

Die Instanz zeigt an, dass das Gerät verbunden wäre.

energymanager.0 | 2022-10-23 10:38:48.344 | error | null
energymanager.0 | 2022-10-23 10:38:33.359 | error | null
energymanager.0 | 2022-10-23 10:38:25.357 | error | Error: Invalid URI "http:///rest/kiwigrid/wizard/devices"

Vielleicht wäre es möglich, den Adapter anzupassen, dass auch dieser Energymanager unterstützt wird? Ist ebenfalls ein Kiwigrid.

**Comment by unltdnetworx** [comment]
> Error: Invalid URI "http:///rest/kiwigrid/wizard/devices"

Das deutet darauf hin, dass keine IP-Adresse im Adapter eingetragen ist. Es muss die IP-Adresse des lokalen Energymanagers eingetragen werden. enviaM scheint wohl auch die Solarwatt-Lösung zu verwenden, also sollte es grundsätzlich funktionieren.

**Comment by Smarty0815** [comment]
Ja, anschließend ist die IP drin und die weiteren Meldungen mit Null folgen.

**Comment by Smarty0815** [comment]
Wenn ich manuell die Adresse http://10.0.1.102/rest/kiwigrid/wizard/devices aufrufe, also im Browser, kommt eine leere Seite, falls dies etwas zu sagen hat.

**Comment by unltdnetworx** [comment]
Mit https://... kommt ebenfalls eine leere Seite, oder?
Evtl. hat enviaM den Energymanager auch angepasst und der Adapter kann deswegen nicht damit umgehen.

Gibt es im ioBroker-Forum dazu evtl. Erkenntnisse, bzw. nutzt jemand den enviaM-Energymanager? Bei einem neuem Thread mich bitte mit @unltdnetworx erwähnen. Würde mich interessieren.

**Comment by Smarty0815** [comment]
https:// geht nicht, Seite nicht gefunden. in ioBroker-Forum hatte ich nix finden können.

**Comment by unltdnetworx** [comment]
Da ich keinen Zugriff auf ein Gerät dieser Marke habe, bitte mal dort nachfragen. Evtl. hat jemand damit Erfahrung.
