### ISSUE TITLE
more numbers

### ISSUE THREAD

**Issue by flinke-flasche** [unltdnetworx/ioBroker.energymanager#4]
Hello,
thanks for your adapter.
Is it possible to display more than two digits after the colon? And not rounded?

Thank you

**Comment by unltdnetworx** [comment]
Hello,
of course it is possible. Will add this possibility in near version.

Hallo,
das ist natürlich möglich, da die Werte ja erst im Adapter gerundet werden. Ich werde diese Möglichkeit bei Gelegenheit als Auswahl in der Oberfläche zur Verfügung stellen.
Rein aus Interesse, wofür braucht man nicht gerundete Werte?

**Comment by flinke-flasche** [comment]
Hi,
das wäre super wenn es das als Option geben würde.
Bin es gewöhnt die Werte in Watt zu haben (kiwigrid und meinsolar.eon.de).
Ist dann auch etwas genauer beim Speicher.

DANKE

**Comment by flinke-flasche** [comment]
Hab noch ne Frage. 
Werden alle Daten komplett ausgelesen?
Auf meinsolar.eon.de sehe ich auch noch den Tagesverbrauch finde die aber nicht im Adapter.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unltdnetworx** [comment]
Ja, es werden alle Daten ausgelesen.

Wenn du einen Tagesverbrauch haben willst, dann musst du diesen selbst loggen. Etwa mit dem SQL-Adapter. Etwas anderes macht die Cloud von E.ON auch nicht. Die speichern nur deine Verbäuche und rechnen sie am Tagesende bzw. Live zusammen.

**Comment by flinke-flasche** [comment]
Funktioniert einwandfrei. 
Hab den Adapter komplett deinstalliert und den neuen installiert. 
Bei mir war Standard die Rundung deaktiviert. 

Danke und ein schönes Fest 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unltdnetworx** [comment]
In den Einstellungen steht erst mal nichts, das stimmt. Aber es ist egal, ob etwas ausgewählt ist oder Runden auf Ja steht. Nur bei explizit Nein wird nicht gerundet.
