### ISSUE TITLE
States get deleted when adapter is stopped or has connection problems

### ISSUE THREAD

**Issue by randomname32** [unltdnetworx/ioBroker.energymanager#44]
When the adapter loses connection to the energymeter (log: `Error: connect ETIMEDOUT 192.168.188.41:80`")
or when the adapter is stopped manually, the states seem to be set to an undefined value. All states under energymanager.0.* have the value "null".
This messes up the aliases and result in lots of warning and error logs from other adapters:

`lovelace.0 | 2023-03-13 23:51:57.727 | info | state alias.0.PV.PowerConsumed deleted`
`javascript.0 | 2023-03-13 23:52:00.011 | warn | getState "alias.0.NSPanel.1.ScreensaverEntities.PV_consumed" not found (3)`

Do the states get deleted on purpose? Is there a way to deactivate this behavior? For me it would be better to keep the states with their last updated value until new updates arrive. 

I'm using version 1.3.4 of the adapter

**Comment by randomname32** [comment]
I should have read the sourcecode before filing a bug... 
https://github.com/unltdnetworx/ioBroker.energymanager/blob/master/main.js#L110

If you don't mind I will try to fix it myself and create a PR for this issue?

**Comment by unltdnetworx** [comment]
Yes, there was a problem if the value doesn't expire. But not sure what it was.
Maybe I can bring in a custom field to switch between expiring or disabling it.

But I am a little busy right now.

**Comment by randomname32** [comment]
I created a PR: https://github.com/unltdnetworx/ioBroker.energymanager/pull/45
We can continue the discussion over there whenever you get some free time.

**Comment by unltdnetworx** [comment]
Merge into main. Will be released if stability is confirmed.
